-- Adminer 4.6.3 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP DATABASE IF EXISTS `test`;
CREATE DATABASE `test` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `test`;

DROP TABLE IF EXISTS `mytable`;
CREATE TABLE `mytable` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(35) DEFAULT NULL,
  `Year` int(11) DEFAULT NULL,
  `Rated` varchar(5) DEFAULT NULL,
  `Released` varchar(11) DEFAULT NULL,
  `Runtime` varchar(7) DEFAULT NULL,
  `Genre` varchar(42) DEFAULT NULL,
  `Director` varchar(24) DEFAULT NULL,
  `Writer` varchar(601) DEFAULT NULL,
  `Actors` varchar(69) DEFAULT NULL,
  `Plot` varchar(235) DEFAULT NULL,
  `Language` varchar(48) DEFAULT NULL,
  `Country` varchar(14) DEFAULT NULL,
  `Awards` varchar(66) DEFAULT NULL,
  `Poster` varchar(130) DEFAULT NULL,
  `Metascore` varchar(3) DEFAULT NULL,
  `imdbRating` varchar(3) DEFAULT NULL,
  `imdbVotes` varchar(9) DEFAULT NULL,
  `imdbID` varchar(9) DEFAULT NULL,
  `Type` varchar(5) DEFAULT NULL,
  `DVD` varchar(11) DEFAULT NULL,
  `BoxOffice` varchar(12) DEFAULT NULL,
  `Production` varchar(20) DEFAULT NULL,
  `Website` varchar(56) DEFAULT NULL,
  `Response` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

TRUNCATE `mytable`;
INSERT INTO `mytable` (`Id`, `Title`, `Year`, `Rated`, `Released`, `Runtime`, `Genre`, `Director`, `Writer`, `Actors`, `Plot`, `Language`, `Country`, `Awards`, `Poster`, `Metascore`, `imdbRating`, `imdbVotes`, `imdbID`, `Type`, `DVD`, `BoxOffice`, `Production`, `Website`, `Response`) VALUES
(1,	'Iron Man',	2008,	'PG-13',	'02 May 2008',	'126 min',	'Action, Adventure, Sci-Fi',	'Jon Favreau',	'Mark Fergus (screenplay), Hawk Ostby (screenplay), Art Marcum (screenplay), Matt Holloway (screenplay), Stan Lee (characters), Don Heck (characters), Larry Lieber (characters), Jack Kirby (characters)',	'Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow',	'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',	'English, Persian, Urdu, Arabic, Hungarian',	'USA',	'Nominated for 2 Oscars. Another 20 wins & 65 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg',	'79',	'7.9',	'835,580',	'tt0371746',	'movie',	'30 Sep 2008',	'$318,298,180',	'Paramount Pictures',	'http://www.ironmanmovie.com/',	'True'),
(2,	'The Incredible Hulk',	2008,	'PG-13',	'13 Jun 2008',	'112 min',	'Action, Adventure, Sci-Fi',	'Louis Leterrier',	'Zak Penn (screenplay), Zak Penn (screen story), Stan Lee (Marvel comic book), Jack Kirby (Marvel comic book)',	'Edward Norton, Liv Tyler, Tim Roth, William Hurt',	'Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into, whenever he loses his temper.',	'English, Portuguese, Spanish',	'USA',	'1 win & 8 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_SX300.jpg',	'61',	'6.8',	'388,957',	'tt0800080',	'movie',	'21 Oct 2008',	'$134,518,390',	'Universal Pictures',	'http://www.incrediblehulk.com/',	'True'),
(3,	'Iron Man 2',	2010,	'PG-13',	'07 May 2010',	'124 min',	'Action, Adventure, Sci-Fi',	'Jon Favreau',	'Justin Theroux (screenplay), Stan Lee (Marvel comic book), Don Heck (Marvel comic book), Larry Lieber (Marvel comic book), Jack Kirby (Marvel comic book)',	'Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson',	'With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father\'s legacy.',	'English, French, Russian',	'USA',	'Nominated for 1 Oscar. Another 7 wins & 42 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg',	'57',	'7.0',	'635,948',	'tt1228705',	'movie',	'28 Sep 2010',	'$312,057,433',	'Paramount Studios',	'http://www.ironmanmovie.com/',	'True'),
(4,	'Thor',	2011,	'PG-13',	'06 May 2011',	'115 min',	'Action, Adventure, Fantasy, Sci-Fi',	'Kenneth Branagh',	'Ashley Miller (screenplay), Zack Stentz (screenplay), Don Payne (screenplay), J. Michael Straczynski (story), Mark Protosevich (story), Stan Lee (comic book), Larry Lieber (comic book), Jack Kirby (comic book)',	'Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins',	'The powerful, but arrogant god Thor, is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.',	'English',	'USA',	'5 wins & 30 nominations.',	'https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg',	'57',	'7.0',	'661,810',	'tt0800369',	'movie',	'13 Sep 2011',	'$181,015,141',	'Paramount Pictures',	'http://thor.marvel.com/',	'True'),
(5,	'Captain America: The First Avenger',	2011,	'PG-13',	'22 Jul 2011',	'124 min',	'Action, Adventure, Sci-Fi',	'Joe Johnston',	'Christopher Markus (screenplay), Stephen McFeely (screenplay), Joe Simon (comic books), Jack Kirby (comic books)',	'Chris Evans, Hayley Atwell, Sebastian Stan, Tommy Lee Jones',	'Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a Super-Soldier serum. But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.',	'English, Norwegian, French',	'USA',	'3 wins & 46 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_SX300.jpg',	'66',	'6.9',	'641,472',	'tt0458339',	'movie',	'25 Oct 2011',	'$176,636,816',	'Paramount Pictures',	'http://captainamerica.marvel.com/',	'True'),
(6,	'The Avengers',	2012,	'PG-13',	'04 May 2012',	'143 min',	'Action, Adventure, Sci-Fi',	'Joss Whedon',	'Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)',	'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',	'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',	'English, Russian, Hindi',	'USA',	'Nominated for 1 Oscar. Another 38 wins & 79 nominations.',	'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',	'69',	'8.1',	'1,150,578',	'tt0848228',	'movie',	'25 Sep 2012',	'$623,279,547',	'Walt Disney Pictures',	'http://marvel.com/avengers_movie',	'True'),
(7,	'Iron Man 3',	2013,	'PG-13',	'03 May 2013',	'130 min',	'Action, Adventure, Sci-Fi',	'Shane Black',	'Drew Pearce (screenplay by), Shane Black (screenplay by), Stan Lee (based on the Marvel comic book by), Don Heck (based on the Marvel comic book by), Larry Lieber (based on the Marvel comic book by), Jack Kirby (based on the Marvel comic book by), Warren Ellis (based on the Extremis mini-series written by), Adi Granov (based on the Extremis mini-series illustrated by)',	'Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce',	'When Tony Stark\'s world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.',	'English',	'China, USA',	'Nominated for 1 Oscar. Another 17 wins & 61 nominations.',	'https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg',	'62',	'7.2',	'672,550',	'tt1300854',	'movie',	'24 Sep 2013',	'$408,992,272',	'Walt Disney Pictures',	'http://IronManMovie3.com',	'True'),
(8,	'Thor: The Dark World',	2013,	'PG-13',	'08 Nov 2013',	'112 min',	'Action, Adventure, Fantasy',	'Alan Taylor',	'Christopher L. Yost (screenplay by), Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Don Payne (story by), Robert Rodat (story by), Stan Lee (based on the Marvel comics by), Larry Lieber (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Walter Simonson (character created by: Malekith)',	'Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins',	'When Dr. Jane Foster gets cursed with a powerful entity known as the Aether, Thor is heralded of the cosmic event known as the Convergence and the genocidal Dark Elves.',	'English',	'USA',	'3 wins & 21 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_SX300.jpg',	'54',	'7.0',	'521,404',	'tt1981115',	'movie',	'25 Feb 2014',	'$206,360,018',	'Walt Disney Pictures',	'http://www.facebook.com/ThorMovie',	'True'),
(9,	'Captain America: The Winter Soldier',	2014,	'PG-13',	'04 Apr 2014',	'136 min',	'Action, Adventure, Sci-Fi, Thriller',	'Anthony Russo, Joe Russo',	'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Joe Simon (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)',	'Chris Evans, Samuel L. Jackson, Scarlett Johansson, Robert Redford',	'As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.',	'English, French',	'USA',	'Nominated for 1 Oscar. Another 5 wins & 50 nominations.',	'https://m.media-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SX300.jpg',	'70',	'7.8',	'638,609',	'tt1843866',	'movie',	'09 Sep 2014',	'$228,636,083',	'Walt Disney Pictures',	'http://marvel.com/captainamerica',	'True'),
(10,	'Guardians of the Galaxy',	2014,	'PG-13',	'01 Aug 2014',	'121 min',	'Action, Adventure, Comedy, Sci-Fi',	'James Gunn',	'James Gunn, Nicole Perlman, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Bill Mantlo (character created by: Rocket Raccoon), Keith Giffen (character created by: Rocket Raccoon), Jim Starlin (characters created by: Drax the Destroyer, Gamora & Thanos), Steve Englehart (character created by: Star-Lord), Steve Gan (character created by: Star-Lord), Steve Gerber (character created by: Howard the Duck), Val Mayerik (character created by: Howard the Duck)',	'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',	'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.',	'English',	'USA',	'Nominated for 2 Oscars. Another 52 wins & 99 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg',	'76',	'8.1',	'913,669',	'tt2015381',	'movie',	'09 Dec 2014',	'$270,592,504',	'Walt Disney Pictures',	'https://www.marvel.com/movies/guardians-of-the-galaxy',	'True'),
(11,	'Avengers: Age of Ultron',	2015,	'PG-13',	'01 May 2015',	'141 min',	'Action, Adventure, Sci-Fi',	'Joss Whedon',	'Joss Whedon, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (character created by: Captain America), Jack Kirby (character created by: Captain America), Jim Starlin (character created by: Thanos)',	'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans',	'When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it\'s up to Earth\'s mightiest heroes to stop the villainous Ultron from enacting his terrible plan.',	'English, Korean',	'USA',	'7 wins & 45 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg',	'66',	'7.4',	'632,930',	'tt2395427',	'movie',	'02 Oct 2015',	'$429,113,729',	'Walt Disney Pictures',	'http://marvel.com/avengers',	'True'),
(12,	'Ant-Man',	2015,	'PG-13',	'17 Jul 2015',	'117 min',	'Action, Adventure, Comedy, Sci-Fi',	'Peyton Reed',	'Edgar Wright (screenplay by), Joe Cornish (screenplay by), Adam McKay (screenplay by), Paul Rudd (screenplay by), Edgar Wright (story by), Joe Cornish (story by), Stan Lee (based on the Marvel comics by), Larry Lieber (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)',	'Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll',	'Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.',	'English',	'USA',	'Nominated for 1 BAFTA Film Award. Another 3 wins & 32 nominations.',	'https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg',	'64',	'7.3',	'476,090',	'tt0478970',	'movie',	'08 Dec 2015',	'$138,002,223',	'Disney/Marvel',	'http://www.facebook.com/antman',	'True'),
(13,	'Captain America: Civil War',	2016,	'PG-13',	'06 May 2016',	'147 min',	'Action, Adventure, Sci-Fi',	'Anthony Russo, Joe Russo',	'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Joe Simon (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)',	'Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan',	'Political involvement in the Avengers\' affairs causes a rift between Captain America and Iron Man.',	'English, German, Xhosa, Russian, Romanian, Hindi',	'USA, Germany',	'16 wins & 65 nominations.',	'https://m.media-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_SX300.jpg',	'75',	'7.8',	'552,484',	'tt3498820',	'movie',	'13 Sep 2016',	'$408,080,554',	'Walt Disney Pictures',	'http://marvel.com/captainamerica#/home',	'True'),
(14,	'Doctor Strange',	2016,	'PG-13',	'04 Nov 2016',	'115 min',	'Action, Adventure, Fantasy, Sci-Fi',	'Scott Derrickson',	'Jon Spaihts, Scott Derrickson, C. Robert Cargill, Stan Lee (based on the Marvel comics by), Steve Ditko (based on the Marvel comics by)',	'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong',	'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.',	'English',	'USA',	'Nominated for 1 Oscar. Another 20 wins & 64 nominations.',	'https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg',	'72',	'7.5',	'485,846',	'tt1211837',	'movie',	'28 Feb 2017',	'$232,630,718',	'Walt Disney Pictures',	'http://marvel.com/doctorstrange',	'True'),
(15,	'Guardians of the Galaxy Vol. 2',	2017,	'PG-13',	'05 May 2017',	'136 min',	'Action, Adventure, Comedy, Sci-Fi',	'James Gunn',	'James Gunn, Dan Abnett (based on the Marvel comics by), Andy Lanning (based on the Marvel comics by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Jim Starlin (Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Steve Gerber (Howard the Duck created by), Val Mayerik (Howard the Duck created by)',	'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel',	'The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord\'s encounter with his father the ambitious celestial being Ego.',	'English',	'USA',	'Nominated for 1 Oscar. Another 12 wins & 42 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg',	'67',	'7.7',	'449,175',	'tt3896198',	'movie',	'22 Aug 2017',	'$389,804,217',	'Walt Disney Pictures',	'https://marvel.com/guardians',	'True'),
(16,	'Thor: Ragnarok',	2017,	'PG-13',	'03 Nov 2017',	'130 min',	'Action, Adventure, Comedy, Fantasy, Sci-Fi',	'Taika Waititi',	'Eric Pearson, Craig Kyle, Christopher L. Yost, Stan Lee (based on the Marvel comics by), Larry Lieber (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)',	'Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba',	'Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.',	'English',	'USA, Australia',	'5 wins & 30 nominations.',	'https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SX300.jpg',	'74',	'7.9',	'439,344',	'tt3501632',	'movie',	'06 Mar 2018',	'$314,971,245',	'Walt Disney Pictures',	'http://movies.disney.com/thor-ragnarok',	'True'),
(17,	'Black Panther',	2018,	'PG-13',	'16 Feb 2018',	'134 min',	'Action, Adventure, Sci-Fi',	'Ryan Coogler',	'Ryan Coogler, Joe Robert Cole, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel Comics by)',	'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o, Danai Gurira',	'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.',	'English, Swahili, Nama, Xhosa, Korean',	'USA',	'14 nominations.',	'https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg',	'88',	'7.3',	'469,075',	'tt1825683',	'movie',	'15 May 2018',	'$501,105,037',	'Marvel Studios',	'https://www.marvel.com/movies/black-panther',	'True'),
(18,	'Avengers: Infinity War',	2018,	'PG-13',	'27 Apr 2018',	'149 min',	'Action, Adventure, Fantasy, Sci-Fi',	'Anthony Russo, Joe Russo',	'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos, Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)',	'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans',	'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',	'English',	'USA',	'N/A',	'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg',	'68',	'8.5',	'592,755',	'tt4154756',	'movie',	'14 Aug 2018',	'$664,987,816',	'Walt Disney Pictures',	'http://marvel.com/movies/movie/223/avengers_infinity_war',	'True'),
(19,	'Captain Marvel',	2019,	'PG-13',	'08 Mar 2019',	'124 min',	'Action, Adventure, Sci-Fi',	'Anna Boden, Ryan Fleck',	'Anna Boden (screenplay by), Ryan Fleck (screenplay by), Geneva Robertson-Dworet (screenplay by), Nicole Perlman (story by), Meg LeFauve (story by), Anna Boden (story by), Ryan Fleck (story by), Geneva Robertson-Dworet (story by)',	'Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law',	'Carol Danvers becomes one of the universe\'s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.',	'English',	'USA',	'N/A',	'https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg',	'65',	'6.9',	'80,858',	'tt4154664',	'movie',	'N/A',	'N/A',	'Marvel Studios',	'https://movies.disney.com/captain-marvel',	'True'),
(20,	'Avengers: Endgame',	2019,	'N/A',	'26 Apr 2019',	'N/A',	'Action, Adventure, Fantasy, Sci-Fi',	'Anthony Russo, Joe Russo',	'Christopher Markus, Stephen McFeely, Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Jim Starlin (comic book)',	'Bradley Cooper, Brie Larson, Chris Hemsworth, Chris Evans',	'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos\' actions and restore order to the universe.',	'English',	'USA',	'N/A',	'https://m.media-amazon.com/images/M/MV5BNGZiMzBkZjMtNjE3Mi00MWNlLWIyYjItYTk3MjY0Yjg5ODZkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg',	'N/A',	'N/A',	'N/A',	'tt4154796',	'movie',	'N/A',	'N/A',	'Marvel Studios',	'N/A',	'True');

-- 2019-03-16 21:36:37
